version: '3.4'

services:
  golinks.webapi:
    image: ${DOCKER_REGISTRY-}golinkswebapi
    build:
      context: .
      dockerfile: Golinks.WebAPI/Dockerfile
    depends_on:
      - golinks.postgres
    networks:
      - golinks_network

  golinks.postgres:
    image: postgres:16.4
    container_name: golinks.postgres
    environment:
      POSTGRES_USER: golinks_app_user
      POSTGRES_PASSWORD: YourStrong!Passw0rd
      POSTGRES_DB: golinks
    ports:
      - "5432:5432"
    networks:
      - golinks_network
    volumes:
      - golinks_postgres:/var/lib/postgresql/data

  golinks.adminer:
    image: adminer:latest
    container_name: golinks.adminer
    ports:
      - "8080:8080"
    depends_on:
      - golinks.postgres
    networks:
      - golinks_network

networks:
  golinks_network:
    driver: bridge

volumes:
  golinks_postgres:
  