version: '3.4'

services:
  golinks.webapi:
    image: ${DOCKER_REGISTRY-}golinkswebapi
    build:
      context: .
      dockerfile: Golinks.WebAPI/Dockerfile
    depends_on:
      - golinks.postgres
  
  golinks.postgres:
    image: postgres:16.4
    container_name: golinks.postgres
    environment:
      POSTGRES_USER: golinks_app_user
      POSTGRES_PASSWORD: YourStrong!Passw0rd
      POSTGRES_DB: golinks
    ports:
      - "5432:5432"
  
  golinks.adminer:
    image: adminer:latest
    container_name: golinks.adminer
    ports:
      - "8080:8080"
    depends_on:
      - golinks.postgres

